#!/usr/bin/node

import { writeFile } from 'node:fs/promises';
import { Readable } from 'node:stream';
import wallpaper from '../assets/wallpaper.json' with { type: 'json' };

try {

    const mapsApi = new URL('https://trackmania.exchange/api/maps')
    mapsApi.search = new URLSearchParams({
        count: 1,
        author: 'forsureitsme',
        fields: ['MapId'],
        order1: 6 // Newest Uploaded
    }).toString();

    const data = await fetch(mapsApi).then(r => r.json());

    const mapId = data.Results[0].MapId;

    if (!mapId || mapId === wallpaper?.mapId) {
        process.exit();
    }

    const response = await fetch(`https://trackmania.exchange/mapimage/${mapId}/1`);
    const stream = Readable.fromWeb(response.body);
    await writeFile('../assets/wallpaper', stream);
    await writeFile('../assets/wallpaper.json', JSON.stringify({ mapId }));
} catch (e) {
    console.warn(e);
}